// فلسطين بلاتفورم - طبقة مشتركة للنسخة الجديدة
window.PP_CONFIG={SUPABASE_URL:"https://sesbumfedusbjevbsyzl.supabase.co",SUPABASE_KEY:"sb_publishable_0sJrbh73jLip3O5OtJkc_A_9F6OPWQK"};
window.ppClient=window.supabase?.createClient(window.PP_CONFIG.SUPABASE_URL,window.PP_CONFIG.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.ppEsc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
window.ppUser=async()=>{if(!window.ppClient)return null;const {data}=await ppClient.auth.getUser();return data?.user||null};
window.ppProfile=async(id)=>{const uid=id||(await ppUser())?.id;if(!uid)return null;const {data}=await ppClient.from('profiles').select('id,full_name,phone,city,avatar_url,role,status').eq('id',uid).maybeSingle();return data||null};
window.ppRoleLabel=r=>({admin:'مدير عام',manager:'مدير',editor:'محرر',moderator:'مشرف',places_manager:'مدير المواقع',ads_manager:'مدير الإعلانات',member:'عضو',user:'عضو'})[r]||'عضو';
window.ppCan=async permission=>{try{const {data,error}=await ppClient.rpc('has_permission',{permission_code:permission});return !error&&data===true}catch(e){return false}};
window.ppRequire=async permission=>{const u=await ppUser();if(!u){location.href='login.html';return null}if(permission && !(await ppCan(permission))){document.body.innerHTML='<main style="font-family:Arial;text-align:center;padding:60px"><h2>⛔ لا تملك الصلاحية</h2><a href="index.html">العودة للرئيسية</a></main>';return null}return u};
window.ppPublicVideo=async url=>{if(!url)return null;if(url.includes('/storage/v1/object/public/'))return url;const m=url.match(/\/storage\/v1\/object\/([^/]+)\/(.+)$/);if(!m)return url;const bucket=m[1],path=decodeURIComponent(m[2]);try{const {data,error}=await ppClient.storage.from(bucket).createSignedUrl(path,3600);return error?url:data?.signedUrl||url}catch(e){return url}};
window.ppSetupHeader=async()=>{const u=await ppUser();const login=document.getElementById('login');const account=document.getElementById('account');const myads=document.getElementById('myads');const admin=document.getElementById('adminLink');const logout=document.getElementById('logout');if(!u){if(login)login.style.display='inline-block';[account,myads,admin,logout].forEach(x=>x&&(x.style.display='none'));return null}if(login)login.style.display='none';[account,myads,logout].forEach(x=>x&&(x.style.display='inline-block'));const p=await ppProfile(u.id);if(admin)admin.style.display=p&&p.status==='active'&&p.role&&p.role!=='member'&&p.role!=='user'?'inline-block':'none';const n=(p?.full_name||u.email?.split('@')[0]||'المستخدم').trim();const name=document.getElementById('name');const initial=document.getElementById('initial');const avatar=document.getElementById('avatar');if(name)name.textContent=n;if(initial){initial.textContent=n[0]||'م';initial.style.display=avatar&&p?.avatar_url?'none':'flex'}if(avatar&&p?.avatar_url){avatar.src=p.avatar_url;avatar.style.display='block'}if(logout&&!logout.dataset.bound){logout.dataset.bound='1';logout.onclick=async e=>{e.preventDefault();await ppClient.auth.signOut();location.href='index.html'}}return {user:u,profile:p}};
