-- ============================================================
-- فلسطين بلاتفورم V56 - Trust & Safety
-- تشغيل بعد V55
-- ============================================================

-- 1) حقول الثقة والتوثيق في الملفات الشخصية
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_verified boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS verified_at timestamptz,
  ADD COLUMN IF NOT EXISTS verified_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS trust_score integer NOT NULL DEFAULT 0;

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_trust_score_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_trust_score_check CHECK (trust_score >= 0 AND trust_score <= 100);

-- 2) حظر المستخدمين
CREATE TABLE IF NOT EXISTS public.user_blocks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  blocker_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  blocked_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(blocker_id, blocked_id),
  CHECK(blocker_id <> blocked_id)
);
ALTER TABLE public.user_blocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_blocks_select_own ON public.user_blocks;
CREATE POLICY user_blocks_select_own ON public.user_blocks FOR SELECT TO authenticated
USING (blocker_id = auth.uid());
DROP POLICY IF EXISTS user_blocks_insert_own ON public.user_blocks;
CREATE POLICY user_blocks_insert_own ON public.user_blocks FOR INSERT TO authenticated
WITH CHECK (blocker_id = auth.uid() AND blocked_id <> auth.uid());
DROP POLICY IF EXISTS user_blocks_delete_own ON public.user_blocks;
CREATE POLICY user_blocks_delete_own ON public.user_blocks FOR DELETE TO authenticated
USING (blocker_id = auth.uid());
CREATE INDEX IF NOT EXISTS user_blocks_blocker_idx ON public.user_blocks(blocker_id, created_at DESC);
CREATE INDEX IF NOT EXISTS user_blocks_blocked_idx ON public.user_blocks(blocked_id);

-- 3) سجل التدقيق الإداري
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS audit_logs_admin_read ON public.audit_logs;
CREATE POLICY audit_logs_admin_read ON public.audit_logs FOR SELECT TO authenticated
USING (public.has_permission('manage_users'));
CREATE INDEX IF NOT EXISTS audit_logs_created_idx ON public.audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_entity_idx ON public.audit_logs(entity_type, entity_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.write_audit_log(
  p_action text,
  p_entity_type text,
  p_entity_id uuid DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  INSERT INTO public.audit_logs(actor_id, action, entity_type, entity_id, metadata)
  VALUES(auth.uid(), left(p_action,100), left(p_entity_type,50), p_entity_id, coalesce(p_metadata,'{}'::jsonb));
END; $$;
REVOKE ALL ON FUNCTION public.write_audit_log(text,text,uuid,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.write_audit_log(text,text,uuid,jsonb) TO authenticated;

-- 4) توثيق الحسابات عبر صلاحية إدارية
CREATE OR REPLACE FUNCTION public.admin_set_user_verification(
  target_user_id uuid,
  new_verified boolean
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_uid uuid := auth.uid();
BEGIN
  IF NOT public.has_permission('manage_users') THEN RAISE EXCEPTION 'غير مصرح'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id=target_user_id) THEN RAISE EXCEPTION 'المستخدم غير موجود'; END IF;
  UPDATE public.profiles
  SET is_verified=new_verified,
      verified_at=CASE WHEN new_verified THEN now() ELSE NULL END,
      verified_by=CASE WHEN new_verified THEN v_uid ELSE NULL END,
      updated_at=now()
  WHERE id=target_user_id;
  PERFORM public.write_audit_log('user_verification_changed','profile',target_user_id,jsonb_build_object('verified',new_verified));
  RETURN FOUND;
END; $$;
GRANT EXECUTE ON FUNCTION public.admin_set_user_verification(uuid,boolean) TO authenticated;

-- 5) حظر/فك حظر مستخدم بواسطة RPC لتسجيل العملية
CREATE OR REPLACE FUNCTION public.block_user(p_blocked_id uuid)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF auth.uid() IS NULL OR p_blocked_id IS NULL OR p_blocked_id = auth.uid() THEN RAISE EXCEPTION 'مستخدم غير صالح'; END IF;
  INSERT INTO public.user_blocks(blocker_id,blocked_id) VALUES(auth.uid(),p_blocked_id)
  ON CONFLICT(blocker_id,blocked_id) DO NOTHING;
  RETURN true;
END; $$;
GRANT EXECUTE ON FUNCTION public.block_user(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.unblock_user(p_blocked_id uuid)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  DELETE FROM public.user_blocks WHERE blocker_id=auth.uid() AND blocked_id=p_blocked_id;
  RETURN FOUND;
END; $$;
GRANT EXECUTE ON FUNCTION public.unblock_user(uuid) TO authenticated;

-- 6) منع التفاعل المباشر مع مستخدم محظور عند إنشاء محادثة
CREATE OR REPLACE FUNCTION public.can_message_user(p_other_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT auth.uid() IS NOT NULL
     AND p_other_user_id IS NOT NULL
     AND auth.uid() <> p_other_user_id
     AND NOT EXISTS (
       SELECT 1 FROM public.user_blocks b
       WHERE (b.blocker_id=auth.uid() AND b.blocked_id=p_other_user_id)
          OR (b.blocker_id=p_other_user_id AND b.blocked_id=auth.uid())
     );
$$;
GRANT EXECUTE ON FUNCTION public.can_message_user(uuid) TO authenticated;

-- 7) تحسين البلاغات: فهرسة + RPC للمراجعة
ALTER TABLE public.ad_reports
  ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ad_reports_status_created_idx ON public.ad_reports(status, created_at DESC);

CREATE OR REPLACE FUNCTION public.moderate_ad_report(
  p_report_id uuid,
  p_status text,
  p_admin_note text DEFAULT NULL
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_ad_id uuid;
BEGIN
  IF NOT public.has_permission('manage_reports') THEN RAISE EXCEPTION 'غير مصرح'; END IF;
  IF p_status NOT IN ('reviewed','dismissed') THEN RAISE EXCEPTION 'حالة غير صالحة'; END IF;
  SELECT ad_id INTO v_ad_id FROM public.ad_reports WHERE id=p_report_id FOR UPDATE;
  IF v_ad_id IS NULL THEN RAISE EXCEPTION 'البلاغ غير موجود'; END IF;
  UPDATE public.ad_reports
  SET status=p_status,
      admin_note=NULLIF(left(coalesce(p_admin_note,''),2000),''),
      reviewed_by=auth.uid(),
      resolved_at=now()
  WHERE id=p_report_id;
  PERFORM public.write_audit_log('ad_report_moderated','ad_report',p_report_id,jsonb_build_object('status',p_status,'ad_id',v_ad_id));
  RETURN true;
END; $$;
GRANT EXECUTE ON FUNCTION public.moderate_ad_report(uuid,text,text) TO authenticated;

-- 8) إجراءات إدارية للإعلان مع سجل تدقيق
CREATE OR REPLACE FUNCTION public.moderate_ad(
  p_ad_id uuid,
  p_status text
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NOT public.has_permission('moderate_ads') THEN RAISE EXCEPTION 'غير مصرح'; END IF;
  IF p_status NOT IN ('active','hidden','deleted') THEN RAISE EXCEPTION 'حالة غير صالحة'; END IF;
  UPDATE public.ads SET status=p_status WHERE id=p_ad_id;
  IF NOT FOUND THEN RETURN false; END IF;
  PERFORM public.write_audit_log('ad_status_changed','ad',p_ad_id,jsonb_build_object('status',p_status));
  RETURN true;
END; $$;
GRANT EXECUTE ON FUNCTION public.moderate_ad(uuid,text) TO authenticated;

-- 9) سجل تغييرات المستخدمين عبر استبدال RPCs الإدارية الحالية
CREATE OR REPLACE FUNCTION public.admin_set_user_status(target_user_id uuid,new_status text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_old text; v_actor text;
BEGIN
  IF NOT public.has_permission('manage_users') THEN RAISE EXCEPTION 'غير مصرح'; END IF;
  IF new_status NOT IN ('active','suspended') THEN RAISE EXCEPTION 'حالة غير صالحة'; END IF;
  SELECT status, role INTO v_old, v_actor FROM public.profiles WHERE id=target_user_id FOR UPDATE;
  IF NOT FOUND THEN RETURN false; END IF;
  UPDATE public.profiles SET status=new_status,updated_at=now() WHERE id=target_user_id;
  PERFORM public.write_audit_log('user_status_changed','profile',target_user_id,jsonb_build_object('from',v_old,'to',new_status,'target_role',v_actor));
  RETURN true;
END; $$;
GRANT EXECUTE ON FUNCTION public.admin_set_user_status(uuid,text) TO authenticated;

-- 10) حماية نشر/تعديل الإعلانات من الحسابات الموقوفة
DROP POLICY IF EXISTS ads_insert_own ON public.ads;
CREATE POLICY ads_insert_own ON public.ads FOR INSERT TO authenticated
WITH CHECK (user_id=auth.uid() AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=auth.uid() AND p.status='active'));

DROP POLICY IF EXISTS ads_update_own ON public.ads;
CREATE POLICY ads_update_own ON public.ads FOR UPDATE TO authenticated
USING ((user_id=auth.uid() AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=auth.uid() AND p.status='active')) OR public.has_permission('manage_ads'))
WITH CHECK ((user_id=auth.uid() AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=auth.uid() AND p.status='active')) OR public.has_permission('manage_ads'));

-- 11) صلاحية جديدة للثقة
INSERT INTO public.platform_permissions(code,label)
VALUES('manage_verification','إدارة التوثيق والثقة')
ON CONFLICT(code) DO NOTHING;
INSERT INTO public.platform_role_permissions(role,permission_code)
VALUES('admin','manage_verification'),('manager','manage_verification')
ON CONFLICT DO NOTHING;

-- ============================================================
-- END V56
-- ============================================================
